language: python

python:
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y realpath

sudo: required

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=reportsystembot;

after_success:
  - coveralls
